"""LeanCTX SDK Stable v1 public surface.

The five Product primitives are ContextSession, ContextSource, ContextView,
ContextPlan, and ContextReceipt. Experimental local-context APIs live under
``leanctx_sdk.preview`` and are outside the Stable compatibility guarantee.
SDK 1.1 adds the separate Agent Tools contract for host-owned agent loops.
"""

__version__ = "1.1.0"

from .agent import (
    AGENT_TOOLS_INTERFACE_VERSION,
    AGENT_TOOLS_SCHEMA_VERSION,
    AGENT_TOOLS_TRANSPORT_VERSION,
    AgentContext,
    AgentMetrics,
    AgentPermissions,
    AsyncAgentContext,
    ExecutionPolicy,
    ReadMode,
    SUPPORTED_AGENT_TOOLS_ENGINE_VERSION,
    ToolResult,
)
from .engine import EngineClient, SubprocessEngineClient
from .errors import (
    AgentPermissionError,
    ArtifactIntegrityError,
    CompatibilityError,
    ConfigurationError,
    EngineError,
    EngineCrashed,
    EngineExecutionError,
    EngineProtocolError,
    EngineRejected,
    EngineTimeout,
    EngineUnavailable,
    FrameworkCompatibilityError,
    FrameworkIntegrationError,
    PolicyAdmissionError,
    RecoveryUnavailableError,
    SDKError,
    SessionStateError,
    SourceUnavailableError,
    UnsupportedEngineError,
    UnsupportedCapabilityError,
    ValidationError,
)
from .protocol import (
    ENGINE_INTERFACE_VERSION,
    SCHEMA_VERSION,
    TRANSPORT_VERSION,
    ContextFailure,
    ContextMeasurement,
    ContextPlan,
    ContextReceiptLink,
    ContextSource,
    ContextView,
    EngineStatus,
    FailureCode,
    Freshness,
    HostOutcome,
    Integrity,
    RecoveredSource,
    SessionState,
)
from .receipt import ContextReceipt
from .session import ContextSession

__all__ = [
    "__version__",
    "AGENT_TOOLS_INTERFACE_VERSION",
    "AGENT_TOOLS_SCHEMA_VERSION",
    "AGENT_TOOLS_TRANSPORT_VERSION",
    "AgentContext",
    "AgentMetrics",
    "AgentPermissionError",
    "AgentPermissions",
    "AsyncAgentContext",
    "ArtifactIntegrityError",
    "CompatibilityError",
    "ConfigurationError",
    "ContextFailure",
    "ContextMeasurement",
    "ContextPlan",
    "ContextReceipt",
    "ContextReceiptLink",
    "ContextSession",
    "ContextSource",
    "ContextView",
    "ENGINE_INTERFACE_VERSION",
    "EngineClient",
    "EngineCrashed",
    "EngineError",
    "EngineExecutionError",
    "EngineProtocolError",
    "EngineRejected",
    "EngineStatus",
    "EngineTimeout",
    "EngineUnavailable",
    "ExecutionPolicy",
    "FailureCode",
    "Freshness",
    "FrameworkCompatibilityError",
    "FrameworkIntegrationError",
    "HostOutcome",
    "Integrity",
    "PolicyAdmissionError",
    "RecoveredSource",
    "ReadMode",
    "RecoveryUnavailableError",
    "SCHEMA_VERSION",
    "SDKError",
    "SessionState",
    "SessionStateError",
    "SourceUnavailableError",
    "SUPPORTED_AGENT_TOOLS_ENGINE_VERSION",
    "SubprocessEngineClient",
    "ToolResult",
    "TRANSPORT_VERSION",
    "UnsupportedEngineError",
    "UnsupportedCapabilityError",
    "ValidationError",
]
