"""Fail-closed inspection for one Product SDK wheel."""

from __future__ import annotations

import argparse
import base64
import csv
import hashlib
import io
import json
import re
import zipfile
from email.parser import BytesParser
from email.policy import default
from pathlib import Path, PurePosixPath
from typing import Dict


_DIST = "thinkery-leanctx-sdk"
_VERSION = "1.1.0"
_PYTHON_REQUIRES = "<3.15,>=3.9"
_DIST_INFO = "thinkery_leanctx_sdk-1.1.0.dist-info"
_DIST_INFO_FILES = {
    "METADATA",
    "RECORD",
    "WHEEL",
    "top_level.txt",
    "licenses/COMMERCIAL-LICENSE.md",
    "licenses/LICENSE",
    "licenses/THIRD_PARTY_NOTICES",
}
_SECRET_PATTERNS = (
    re.compile(rb"-----BEGIN (?:RSA |EC |OPENSSH )?PRIVATE KEY-----"),
    re.compile(rb"\bsk-[A-Za-z0-9_-]{20,}\b"),
    re.compile(rb"\bgh[pousr]_[A-Za-z0-9]{20,}\b"),
)
_HOST_PATHS = (b"/Users/", b"/private/tmp/", b"C:\\Users\\")


def _digest(data: bytes) -> str:
    return hashlib.sha256(data).hexdigest()


def _record_hash(data: bytes) -> str:
    value = base64.urlsafe_b64encode(hashlib.sha256(data).digest()).rstrip(b"=")
    return "sha256=" + value.decode("ascii")


def _canonical_requirement(value: str) -> str:
    """Normalize only formatting that packaging backends vary semantically."""

    result = []
    quote = None
    for character in value:
        if quote is not None:
            if character == quote:
                result.append('"')
                quote = None
            else:
                result.append(character)
        elif character in {'"', "'"}:
            result.append('"')
            quote = character
        elif character.isspace() or character in "()":
            continue
        else:
            result.append(character.lower())
    if quote is not None:
        raise ValueError("unterminated requirement marker literal")
    return "".join(result)


def inspect_wheel(path: Path) -> Dict[str, object]:
    try:
        raw = path.read_bytes()
        archive = zipfile.ZipFile(io.BytesIO(raw))
    except (OSError, zipfile.BadZipFile) as exc:
        raise ValueError("artifact is not a readable wheel") from exc

    with archive:
        names = archive.namelist()
        if not names or len(names) != len(set(names)):
            raise ValueError("wheel entries must be non-empty and unique")
        for name in names:
            pure = PurePosixPath(name)
            if name.endswith("/") or name.startswith("/") or "\\" in name:
                raise ValueError(f"invalid wheel entry: {name}")
            if any(part in {"", ".", ".."} for part in pure.parts):
                raise ValueError(f"unsafe wheel entry: {name}")
            allowed = name.startswith("leanctx_sdk/") or name.startswith(
                _DIST_INFO + "/"
            )
            if not allowed:
                raise ValueError(f"unexpected wheel entry: {name}")
            if name.startswith(_DIST_INFO + "/"):
                leaf = name.removeprefix(_DIST_INFO + "/")
                if leaf not in _DIST_INFO_FILES:
                    raise ValueError(f"unexpected dist-info entry: {name}")
            if name.startswith(("leanctx_sdk/research/", "leanctx_sdk/internal/")):
                raise ValueError(f"private SDK entry is forbidden: {name}")
            if "__pycache__" in pure.parts or pure.suffix in {".pyc", ".pyo"}:
                raise ValueError(f"generated bytecode is forbidden: {name}")

        required = {_DIST_INFO + "/" + item for item in _DIST_INFO_FILES}
        if not required.issubset(names):
            raise ValueError("wheel dist-info allowlist is incomplete")

        contents = {name: archive.read(name) for name in names}
        metadata = BytesParser(policy=default).parsebytes(
            contents[_DIST_INFO + "/METADATA"]
        )
        if metadata.get("Name") != _DIST or metadata.get("Version") != _VERSION:
            raise ValueError(
                "wheel identity does not match the frozen release identity"
            )
        license_text = contents[_DIST_INFO + "/licenses/LICENSE"]
        if not all(
            marker in license_text
            for marker in (
                b"LeanCTX SDK Source License 1.0",
                b"There is no Change Date",
            )
        ):
            raise ValueError("wheel does not contain the reviewed final license")
        commercial_text = contents[_DIST_INFO + "/licenses/COMMERCIAL-LICENSE.md"]
        if not all(
            marker in commercial_text
            for marker in (
                b"Commercial Production licensing",
                b"executed agreement with Thinkery AG",
            )
        ):
            raise ValueError("wheel does not contain the commercial license reference")
        notices = contents[_DIST_INFO + "/licenses/THIRD_PARTY_NOTICES"]
        if not all(
            marker in notices
            for marker in (
                b"LeanCTX SDK v1.1.0",
                b"Third-Party Notices",
                b"exact 41-wheel",
                b"openai-agents 0.8.4",
            )
        ):
            raise ValueError("wheel does not contain the final third-party notices")
        python_requires = metadata.get("Requires-Python", "")
        canonical_python_requires = ",".join(
            sorted(part.strip() for part in python_requires.split(",") if part.strip())
        )
        if canonical_python_requires != _PYTHON_REQUIRES:
            raise ValueError(
                "wheel Python requirement differs from the certified matrix"
            )
        requirements = sorted(
            _canonical_requirement(value)
            for value in metadata.get_all("Requires-Dist", [])
        )
        expected_requirements = sorted(
            _canonical_requirement(value)
            for value in [
                "thinkery-leanctx-engine (==3.10.1) ; extra == 'agent'",
                'thinkery-leanctx-engine-cuda (==3.10.1) ; (platform_system == "Linux" and platform_machine == "x86_64") and extra == \'agent-cuda\'',
                'thinkery-leanctx-engine-windows-gnu (==3.10.1) ; (platform_system == "Windows" and platform_machine == "AMD64") and extra == \'agent-windows-gnu\'',
                "openai (==2.19.0) ; (python_version >= \"3.10\") and extra == 'openai-agents'",
                "openai-agents (==0.8.4) ; (python_version >= \"3.10\") and extra == 'openai-agents'",
                "pydantic (==2.12.3) ; (python_version >= \"3.10\") and extra == 'openai-agents'",
                "requests (==2.33.0) ; (python_version >= \"3.10\") and extra == 'openai-agents'",
                "urllib3 (==2.7.0) ; (python_version >= \"3.10\") and extra == 'openai-agents'",
            ]
        )
        if requirements != expected_requirements:
            raise ValueError("wheel dependency metadata differs from the reviewed pins")

        record_name = _DIST_INFO + "/RECORD"
        rows = list(csv.reader(io.StringIO(contents[record_name].decode("utf-8"))))
        if len(rows) != len(names) or {row[0] for row in rows} != set(names):
            raise ValueError("RECORD does not exactly cover wheel entries")
        for row in rows:
            if len(row) != 3:
                raise ValueError("RECORD row must have exactly three fields")
            name, digest, size = row
            if name == record_name:
                if digest or size:
                    raise ValueError("RECORD self-entry must omit hash and size")
            elif digest != _record_hash(contents[name]) or size != str(
                len(contents[name])
            ):
                raise ValueError(f"RECORD integrity mismatch: {name}")

        for name, content in contents.items():
            if any(pattern.search(content) for pattern in _SECRET_PATTERNS):
                raise ValueError(f"secret-like content in wheel entry: {name}")
            if any(marker in content for marker in _HOST_PATHS):
                raise ValueError(f"host path leaked into wheel entry: {name}")

    return {
        "distribution": _DIST,
        "entries": len(names),
        "sha256": _digest(raw),
        "status": "PASS",
        "version": _VERSION,
    }


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("wheel", type=Path)
    args = parser.parse_args()
    print(json.dumps(inspect_wheel(args.wheel.resolve(strict=True)), sort_keys=True))


if __name__ == "__main__":
    main()
